package commonUtil;

public enum ToRfqParams {
    HEADERID,
    ROW,
    CUSTOMERID,
    SPQCHECKED,
    CUSTACTIVE,
    SALESAREANO,
    CUSTOMERPO,
    CURR,
    REMARK,
    PREORDERTYPE,
    SALESPERSON,
    TOPERSONID,
    ISMODELSELECTED,
    PROCESSAREA,
    SHIPTO,
    CUSTOMERIDTMP,
    INSERT,
    RFQTYPE,
    UPLOAD_TEMP_ID,
    SHIPTOCONTACT,
    SHIPTOCONTACTID,
    PROGRAMNAME,
    ISEMPTYROW
}
