-- 台北半導體生管 NEI 由工單轉請採購流程

 --(1) 開立製造工單 (WIP JIB DISCRETE ) 
    -- 其Routing 皆只有一站 外包站 , 
	-- 故 Routing 於 Operation Resource 會設定外包站對應的外包料件
	-- 可供轉請採購單正確料項之對應 
 --(2) 工單作 Release 
 --(3) 利用 Responsibility(TSC_PO_SEMI_BUYER) 
        --(a).Run Request 作 Requisition Import (TYPE = WIP) 
		--(b).Requisition Summary 選 Import Sorce = WIP 
		                          -- Requestor = Chen%  找出Requisition No.
		--(c).Auto CreateDocument 利用Requisition No.查 Requisition Summary 
		                         --內詳細資訊

--找 Descrete Job 
SELECT * FROM WIP_DISCRETE_JOBS_V WHERE WIP_ENTITY_NAME ='S-50323-1';
SELECT * FROM WIP_DISCRETE_JOBS WHERE WIP_ENTITY_ID =29031;

-- 找 Descrete 對應的 Operation 
SELECT OPERATION_SEQ_NUM,ORGANIZATION_ID,OPERATION_SEQUENCE_ID,STANDARD_OPERATION_ID,
       OPERATION_CODE,DEPARTMENT_ID,DEPARTMENT_CODE,DESCRIPTION,SCHEDULED_QUANTITY,
	   CREATED_BY,CREATION_DATE
  FROM WIP_OPERATIONS_V WHERE WIP_ENTITY_ID=29031;

-- 找 Descrete 對應的 OPeration Resource 
SELECT OPERATION_SEQ_NUM,RESOURCE_SEQ_NUM,RESOURCE_CODE,PURCHASE_ITEM_ID,
       RESOURCE_ID,UOM_CODE,UOM_CLASS,AUTOCHARGE_CODE,DESCRIPTION
 FROM WIP_OPERATION_RESOURCES_V 
WHERE WIP_ENTITY_ID=29031;


-- NBU WIP 已交未交明細報表 

BEGIN
  DBMS_APPLICATION_INFO.SET_CLIENT_INFO('41');
END;

SELECT * FROM WIP_DISCRETE_JOBS_V WHERE WIP_ENTITY_NAME ='S-60270';

SELECT WDJ.WIP_ENTITY_NAME, MSI.SEGMENT1,MSI.DESCRIPTION FROM WIP_DISCRETE_JOBS_V WDJ, MTL_SYSTEM_ITEMS  MSI 
WHERE WDJ.PRIMARY_ITEM_ID = MSI.INVENTORY_ITEM_ID  AND WDJ.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
        AND WDJ.WIP_ENTITY_NAME ='S-60271';

--  找主要工單資訊		
		SELECT WDJ.WIP_ENTITY_NAME, MSI.SEGMENT1,MSI.DESCRIPTION, WRO.ITEM_DESCRIPTION, MIC.SEGMENT1,
		               WDJ.SCHEDULED_START_DATE, WDJ.SCHEDULED_COMPLETION_DATE, WDJ.START_QUANTITY
		  FROM WIP_DISCRETE_JOBS_V WDJ, MTL_SYSTEM_ITEMS  MSI ,
		              WIP_REQUIREMENT_OPERATIONS_V WRO, MTL_ITEM_CATEGORIES_V MIC
WHERE WDJ.PRIMARY_ITEM_ID = MSI.INVENTORY_ITEM_ID  AND WDJ.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
        AND WDJ.WIP_ENTITY_ID = WRO.WIP_ENTITY_ID 
		AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID 
		AND MIC.CATEGORY_SET_NAME ='TSC_Package' AND WDJ.WIP_ENTITY_NAME ='S-60270';

SELECT * FROM WIP_DISCRETE_JOBS WHERE WIP_ENTITY_ID =70943;

SELECT * FROM WIP_REQUIREMENT_OPERATIONS_V WHERE WIP_ENTITY_ID = 70943;
SELECT * FROM WIP_REQUIREMENT_OPERATIONS_V WHERE WIP_ENTITY_ID = 70543;

-- 找 PR 資訊, 透過 WIP_ENTITY_ID
SELECT PRH.*,PRL.* FROM PO_REQUISITION_HEADERS_ALL PRH, PO_REQUISITION_LINES_ALL PRL 
WHERE PRH.REQUISITION_HEADER_ID =PRL.REQUISITION_HEADER_ID 
AND PRH.INTERFACE_SOURCE_CODE ='WIP' AND PRH.ORG_ID = PRL.ORG_ID 
--AND PRL.SOURCE_TYPE_CODE = 'VENDOR' AND PRL.DESTINATION_ORGANIZATION_ID = 49 
AND PRL.WIP_ENTITY_ID = 70543;

-- 找PO資訊,透過PR.PREPARER_ID 與 PO.AGENT_ID
SELECT H.*, L.* FROM PO_HEADERS_ALL H,  PO_LINES_ALL L
 WHERE H.PO_HEADER_ID = L.PO_HEADER_ID 
 AND H.ORG_ID = L.ORG_ID AND H.AGENT_ID=2553 AND L.ITEM_ID = 86544;
 
 -- 關聯PR及PO找其工單資訊
SELECT PRH.SEGMENT1 AS PR,PRL.ITEM_DESCRIPTION,PRL.ITEM_ID,PRL.NEED_BY_DATE, PRL.WIP_ENTITY_ID,
               POH.SEGMENT1 AS PO,POH.PO_HEADER_ID,POH.VENDOR_ID,POL.PO_LINE_ID,POL.QUANTITY, VND.VENDOR_NAME
 FROM PO_REQUISITION_HEADERS_ALL PRH, PO_REQUISITION_LINES_ALL PRL,
             PO_HEADERS_ALL POH,  PO_LINES_ALL POL, PO_VENDORS VND
WHERE PRH.REQUISITION_HEADER_ID =PRL.REQUISITION_HEADER_ID 
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND POH.ORG_ID = POL.ORG_ID AND POH.AGENT_ID= PRH.PREPARER_ID
AND POL.ITEM_ID = PRL.ITEM_ID AND POH.VENDOR_ID = VND.VENDOR_ID
AND PRH.INTERFACE_SOURCE_CODE ='WIP' AND PRH.ORG_ID = PRL.ORG_ID 
--AND PRL.SOURCE_TYPE_CODE = 'VENDOR' AND PRL.DESTINATION_ORGANIZATION_ID = 49 
AND PRL.WIP_ENTITY_ID = 70543;


-- 合併工單及PR,PO關聯資訊

SELECT  WDJ.WIP_ENTITY_NAME, MSI.SEGMENT1,MSI.DESCRIPTION, WRO.ITEM_DESCRIPTION, MIC.SEGMENT1,
		         WDJ.SCHEDULED_START_DATE, WDJ.SCHEDULED_COMPLETION_DATE, WDJ.START_QUANTITY,
				 PRH.SEGMENT1 AS PR,PRL.ITEM_DESCRIPTION,PRL.ITEM_ID,PRL.NEED_BY_DATE, PRL.WIP_ENTITY_ID,
                POH.SEGMENT1 AS PO,POH.PO_HEADER_ID,POH.VENDOR_ID,POL.PO_LINE_ID,POL.QUANTITY, VND.VENDOR_NAME
		  FROM WIP_DISCRETE_JOBS_V WDJ, MTL_SYSTEM_ITEMS  MSI ,
		              WIP_REQUIREMENT_OPERATIONS_V WRO, MTL_ITEM_CATEGORIES_V MIC,
					  PO_REQUISITION_HEADERS_ALL PRH, PO_REQUISITION_LINES_ALL PRL,
                     PO_HEADERS_ALL POH,  PO_LINES_ALL POL, PO_VENDORS VND
WHERE WDJ.PRIMARY_ITEM_ID = MSI.INVENTORY_ITEM_ID  AND WDJ.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
        AND WDJ.WIP_ENTITY_ID = WRO.WIP_ENTITY_ID 
		AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
AND PRH.REQUISITION_HEADER_ID =PRL.REQUISITION_HEADER_ID 
AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
AND POH.ORG_ID = POL.ORG_ID AND POH.AGENT_ID= PRH.PREPARER_ID
AND POL.ITEM_ID = PRL.ITEM_ID AND POH.VENDOR_ID = VND.VENDOR_ID
AND PRH.INTERFACE_SOURCE_CODE ='WIP' AND PRH.ORG_ID = PRL.ORG_ID AND PRL.WIP_ENTITY_ID=	WDJ.WIP_ENTITY_ID
		AND MIC.CATEGORY_SET_NAME ='TSC_Package' AND WDJ.WIP_ENTITY_NAME ='S-60270';


-- 找收料資料依 PO_HEADER_ID 及 PO_LINE_ID
 -- 要 Set Client Infor 
SELECT * FROM RCV_VRC_TXS_V WHERE PO_HEADER_ID = 53037 
AND WIP_ENTITY_ID = 31019
AND PO_LINE_ID = 126882 AND TRANSACTION_TYPE='RECEIVE';  -- 暫收(有帶 WIP_ENTITY_ID)

SELECT * FROM RCV_VRC_TXS_V WHERE PO_HEADER_ID = 53037 
AND WIP_ENTITY_ID = 31019
AND PO_LINE_ID = 126882 AND TRANSACTION_TYPE='ACCEPT';  -- 驗收(允收)

SELECT * FROM RCV_VRC_TXS_V WHERE PO_HEADER_ID = 53037 
AND WIP_ENTITY_ID = 31019
AND PO_LINE_ID = 126882 AND TRANSACTION_TYPE='DELIVER';  -- 交貨(有帶 WIP_ENTITY_ID)
